### ISSUE TITLE
Some issues about performance

### ISSUE THREAD

**Issue by ArSrNa** [festivities/Blender-miHoYo-Shaders#6]
Hi, I use this shader. After binding the head bone, playing, changing the z axis of the Main Light Direction and other operations become particularly slow, but the task manager is not full, rendering is also very difficult. If it takes only 3 seconds to turn off the binding, it takes 20 seconds to turn it on :(((((((
This is my computer configuration
CPU：AMD Ryzen 7 5800H
GPU：NVIDIA RTX 3050
Memory: 16GB

**Comment by ArSrNa** [comment]
![image](https://user-images.githubusercontent.com/42886855/213096566-a0899dc9-cba1-438d-a593-6544530025d4.png)

![image](https://user-images.githubusercontent.com/42886855/213096584-2cfdcc47-866f-4ff4-a0a8-429880d9087c.png)


Turns off
![image](https://user-images.githubusercontent.com/42886855/213096641-c1549879-d568-44e1-8b7a-0f0282f5c89a.png)

![image](https://user-images.githubusercontent.com/42886855/213096659-e8c8bf9d-fc61-4fd3-a96e-abdfd6ea8744.png)

**Comment by festivize** [comment]
This is an unfortunate byproduct of the face shader recalculating every frame. There's not much I can do unless a shader wizard helps me find another way of doing the face shading without drivers. I've thought of using the mesh or head bone's world space rotation but I'd say this way is extremely janky as rotation values can be very inconsistent depending on how the user imports their models into Blender. If anyone out there has a better approach on doing this, feel free to share it in this thread if you don't mind.

**Comment by festivize** [comment]
After some discussion with other Blender users, I can confirm that the MixRGB node _in EEVEE_ calculates both the `Color1` and `Color2` inputs regardless if the factor is a full-on 1 or 0. We'll need either proper optimizations by Blender devs, or a conditional flow node before this problem can be addressed. Thank you for raising this issue.

**Comment by ArSrNa** [comment]
By the way, I've also made a simple tutorial for Chinese people:

[https://cloud.tencent.com/developer/article/2210154](https://cloud.tencent.com/developer/article/2210154)

[https://www.bilibili.com/read/cv21262750](https://www.bilibili.com/read/cv21262750)
