### ISSUE TITLE
How can I import multiple models without affecting each other's materials?

### ISSUE THREAD

**Issue by Hades-Su** [festivities/Blender-miHoYo-Shaders#7]
I'm a blender newbie and I'm wondering how to import multiple models without affecting each other's materials? I'm having issues with the first model after I import the second model

**Comment by Hades-Su** [comment]
![Snipaste_2023-05-10_20-20-07](https://github.com/festivize/Blender-miHoYo-Shaders/assets/40000311/2ad895af-20ff-4e2a-ad04-3342ed6fa17b)

**Comment by Bravco** [comment]
When importing multiple models into Blender, it's essential to ensure that each model's materials are separate and independent from each other. Here's a step-by-step guide to help you import multiple models without affecting each other's materials:

1. Open Blender and create a new scene or open an existing one.
2. Import the first model into Blender by going to "File" -> "Import" -> choose the appropriate file format for your model (such as OBJ, FBX, or STL) and select the file.
3. After importing the first model, make sure that all its materials are correctly assigned to its respective geometry. You can check this by selecting different parts of the model and inspecting the assigned materials in the "Materials" tab of the Properties panel (usually located on the right side of the interface).
4. Now, before importing the second model, make sure you have a clean workspace. You can do this by deselecting everything (press 'A' to select/deselect all) or deleting the first model altogether (press 'X' and confirm deletion).
5. Import the second model by following the same steps as before (File -> Import -> choose the appropriate file format and select the file).
6. After importing the second model, ensure that its materials are correctly assigned as well. Check the assigned materials using the same method mentioned in step 3.

By following these steps, you should be able to import multiple models into Blender without their materials interfering with each other. Each model will have its own set of materials, allowing you to work with them individually.

Note: If you encounter any issues with materials overlapping or being affected by the second model, you might need to check the material settings and adjust them accordingly. Additionally, ensure that the models you are importing have distinct material names to avoid conflicts.
